// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "4284349d-5f71-4a68-b1c5-5882cf54bd88";
const char DEVICE_LOGIN_NAME[]  = "be74704f-7a56-4d8c-885f-4ac501a644cc";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPinLed1Change();

bool pinLed1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(pinLed1, READWRITE, ON_CHANGE, onPinLed1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
